Removelicence
mbc-engineering/log4TC pull request #4
Opened 2021-04-14 16:45 UTC by bqstony

#2 

Also some bugfix and diagnoses from wj

2021-04-14 16:56 UTC, stegm requested changes
Grundsätzlich hab ich kein Problem mit der Lizenz. Ich würde aber vorher gerne die anderen dazu ins Boot holen.

2021-04-14 16:56 UTC, stegm commented on source/Log4Tc/Mbc.Log4Tc.Receiver/AdsLogReceiverService.cs
>              _adsLogReceiver.Dispose();
Ich denke, das sollte hier kein spezifisches Problem sein, aber ich denke es könnte sinnvoll sein, zuerst die ableitende Klasse und dann die Basisklasse zu disposen. Also andersherum als beim erstellen.

2021-04-14 16:56 UTC, stegm commented on source/TwinCat_Lib/log4tc/log4tc/mbc_Log4TC/POUs/FB_Log4TcTask.TcPOU
> +    </LineIds>
Kann man in den Optionen abschalten.

2021-04-14 16:56 UTC, stegm commented on source/TwinCat_Lib/log4tc/log4tc/mbc_Log4TC/POUs/FB_LogEntry.TcPOU
> +(* Deactivate Licence check
Entweder komplett rausnehmen oder nicht. Auf jeden Fall kein Dead-Code.

2021-04-14 16:56 UTC, stegm commented on source/TwinCat_Lib/log4tc/log4tc/mbc_Log4TC/POUs/FB_LogEntry.TcPOU
> +    </LineIds>
Wie oben

2021-04-17 15:58 UTC, bqstony commented
@stegm habe die Feedbacks umgesetzt

2021-04-21 16:37 UTC, merged